#!/bin/sh
#
# Start the network....
#
echo "Network"

case "$1" in
  start)

	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

